apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: knative-route53-ddns
  namespace: knative-route53-ddns
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        app: change-detection
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: knative-route53-ddns
      namespace: knative-route53-ddns
