apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: change-apply
  namespace: knative-route53-ddns
spec:
  broker: knative-route53-ddns
  subscriber:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Service
      name: change-apply
      namespace: knative-route53-ddns