apiVersion: apps/v1
kind: Deployment
metadata:
  name: change-detection
  namespace: knative-route53-ddns
  labels:
    app: change-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: change-detection
  template:
    metadata:
      labels:
        app: change-detection
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: change-detection
        image: bentastic27/knative-route53-ddns-detection:latest
        envFrom:
        - secretRef:
            name: aws-creds
        - configMapRef:
            name: knative-route53-ddns
        resources:
          requests:
            cpu: 50m
            memory: 64M
          limits:
            cpu: 100m
            memory: 128M
