name: change-apply image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'change-apply/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'change-apply/**'

jobs:
  change-appl:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:change-apply"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            bentastic27/knative-route53-ddns-apply:${{ github.sha }}
            bentastic27/knative-route53-ddns-apply:latest
